#!/usr/bin/env bash
# Capture a working Armbian Move into a redistributable bundle.
#
# The bundle is what install.sh unpacks onto a stock Move. It is built FROM a
# device that already runs the stack, because that device is the only complete
# specification of it: the kernel, the overlays, the RT tuning and every package
# installed along the way. Rebuilding from the Armbian sources reproduces the
# kernel but not the afternoon of fixes on top of it.
#
#   ./armbian/build-bundle.sh [host] [outdir]
#
# What is deliberately NOT captured, and why:
#   /opt/move        Ableton's proprietary software. Copied from the user's own
#                    device at install time instead — never redistributed.
#   /data, move-data the user's projects and samples.
#   NM connections   contains the Wi-Fi PSK.
#   ssh host keys    a shared host key across installs is a real vulnerability.
#   machine-id       must be unique per install or DHCP leases collide.
set -euo pipefail

HOST="${1:-move.local}"
OUT="${2:-$(cd "$(dirname "$0")/.." && pwd)/bundle/armbian}"
SSH="ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no root@$HOST"

b()  { printf '\033[1m%s\033[0m\n' "$*"; }
die() { printf '\033[31mFATAL: %s\033[0m\n' "$*" >&2; exit 1; }

b "== source: root@$HOST"
$SSH true 2>/dev/null || die "cannot ssh to root@$HOST"
KVER=$($SSH 'uname -r')
case "$KVER" in
    *current-bcm2711*) ;;
    *) die "root@$HOST is not running the Move Armbian kernel (uname -r = $KVER)" ;;
esac
$SSH 'test -e /dev/ablspi0.0' || die "no /dev/ablspi0.0 — is this a Move?"
echo "   kernel $KVER"

mkdir -p "$OUT/boot/overlays"

# ---------------------------------------------------------------- boot payload
b "== boot payload (partition 1)"
for f in armbian-Image bcm2711-rpi-cm4-armbian.dtb armbian-cmdline.txt; do
    $SSH "cat /boot/firmware/$f" > "$OUT/boot/$f" || die "missing /boot/firmware/$f"
    echo "   $f  $(wc -c < "$OUT/boot/$f") bytes"
done
for f in ablspi-move-cm4.dtbo move-spidev0-off.dtbo ablspi.dtbo; do
    $SSH "cat /boot/firmware/overlays/$f" > "$OUT/boot/overlays/$f" || die "missing overlay $f"
    echo "   overlays/$f"
done
# config.txt is generated by the converter (it must reference the right kernel),
# so we ship the canonical one from the repo, not the device's.
cp "$(dirname "$0")/boot/config.txt.armbian" "$OUT/boot/config.txt.armbian"

# ---------------------------------------------------------------------- rootfs
b "== rootfs (this is the long one — a couple of GB, gzip on the device)"
# gzip, not zstd: a STOCK Move has no zstd and no apt to get one, and the
# converter has to be able to unpack this with nothing but busybox-era tools.
EXCLUDES=(
    ./proc/'*' ./sys/'*' ./dev/'*' ./run/'*' ./tmp/'*' ./mnt/'*' ./media/'*'
    ./lost+found ./swapfile ./vmlinuz.old
    ./data ./data/'*' ./var/lib/move-data ./var/lib/move-data/'*'
    ./opt/move ./opt/move/'*'
    # Ableton's dbus activation files: theirs, and meaningless without /opt/move.
    # Carried across from the user's own device by the converter, like /opt/move.
    ./usr/share/dbus-1/system-services/com.ableton.'*'
    ./etc/dbus-1/system.d/move.conf
    './*/__pycache__' './*/*/__pycache__'
    ./etc/NetworkManager/system-connections ./etc/NetworkManager/system-connections/'*'
    ./etc/ssh/ssh_host_'*'
    ./root/.ssh ./root/.ssh/'*' ./home/'*'/.ssh ./home/'*'/.ssh/'*'
    ./etc/machine-id ./var/lib/dbus/machine-id
    ./var/log/'*' ./var/tmp/'*' ./var/cache/apt/archives/'*.deb'
    ./var/lib/apt/lists/'*'
)
EXARGS=""
for e in "${EXCLUDES[@]}"; do EXARGS="$EXARGS --exclude=$e"; done

$SSH "tar -C / -czf - $EXARGS --one-file-system --numeric-owner ." > "$OUT/rootfs.tar.gz"
echo "   rootfs.tar.gz  $(du -h "$OUT/rootfs.tar.gz" | cut -f1)"

# Guard: a rootfs that somehow swept up the excluded trees is not shippable.
b "== verifying the tarball carries nothing it shouldn't"
LEAK=$(tar -tzf "$OUT/rootfs.tar.gz" 2>/dev/null | grep -E \
   '^\./(opt/move/|data/|var/lib/move-data/|etc/NetworkManager/system-connections/.|etc/ssh/ssh_host_|root/\.ssh/|usr/share/dbus-1/system-services/com\.ableton\.|etc/dbus-1/system\.d/move\.conf)' \
   | head -5 || true)
[ -z "$LEAK" ] || { echo "$LEAK"; die "excluded content present in the tarball"; }
echo "   clean: no proprietary, user or secret content"

# The mirror of the leak check: prove the pieces the system cannot boot without
# actually made it in. data.mount is the one that matters most -- without it
# /data is an empty directory after conversion and the whole instrument is gone.
for must in ./etc/fstab ./usr/lib/systemd/system/data.mount \
            ./etc/systemd/system/local-fs.target.wants/data.mount \
            ./etc/systemd/system/jackd-move.service ./usr/bin/python3; do
    tar -tzf "$OUT/rootfs.tar.gz" "$must" >/dev/null 2>&1 \
      || die "rootfs is missing $must — the bundle would not boot into a usable system"
done
echo "   complete: fstab, data.mount (+its enable symlink), jackd-move, python3"

# -------------------------------------------------------------------- manifest
b "== manifest"
{
    echo "# PoundHard Armbian bundle"
    echo "kernel=$KVER"
    echo "built_from=$HOST"
    echo "rootfs_bytes=$(wc -c < "$OUT/rootfs.tar.gz")"
} > "$OUT/MANIFEST"
( cd "$OUT" && find . -type f ! -name SHA256SUMS -exec shasum -a 256 {} + | sort -k2 > SHA256SUMS )
echo "   $(wc -l < "$OUT/SHA256SUMS") files hashed"

b "== done"
echo "   $OUT"
du -sh "$OUT"
